import { Product, Category, BlogPost } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'premium',
    name: 'Premium Mangoes',
    description: 'Export quality hand-picked mangoes.',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    slug: 'premium-mangoes'
  },
  {
    id: 'seasonal',
    name: 'Seasonal Boxes',
    description: 'Freshly harvested seasonal varieties.',
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    slug: 'seasonal-boxes'
  },
  {
    id: 'gift',
    name: 'Gift Packs',
    description: 'Luxury packaging for your loved ones.',
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    slug: 'gift-packs'
  },
  {
    id: 'bulk',
    name: 'Bulk Orders',
    description: 'Special rates for events and corporate.',
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    slug: 'bulk-orders'
  }
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Sindhri Box',
    variety: 'Sindhri',
    price: 1850,
    originalPrice: 2200,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'The queen of mangoes from Sindh. Known for its honey-like sweetness and smooth texture.',
    fullDescription: 'Sindhri is the most famous variety from Pakistan, particularly from the Mirpur Khas region. It is known for its large size, yellow skin when ripe, and incredibly sweet, fiberless pulp. Perfect for milkshakes or eating fresh.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Mirpur Khas, Sindh',
    category: 'Premium',
    isBestSeller: true,
    nutrition: { calories: 60, vitaminC: '60%', fiber: '1.6g' },
    reviews: [
      { id: 'r1', userName: 'Ahmed Khan', rating: 5, comment: 'Best Sindhri I have ever had! So sweet.', date: '2024-06-15' }
    ]
  },
  {
    id: '2',
    name: 'Export Quality Chaunsa',
    variety: 'Chaunsa',
    price: 2450,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'World famous Pakistani Chaunsa. Exceptionally sweet and aromatic.',
    fullDescription: 'Chaunsa mango of Pakistan is one of the worlds top available varieties. It is uniquely aromatic and sweet. The name was given by Sher Shah Suri after defeating Humayun at Chaunsa.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Multan, Punjab',
    category: 'Premium',
    isBestSeller: true,
    nutrition: { calories: 65, vitaminC: '70%', fiber: '1.8g' }
  },
  {
    id: '3',
    name: 'Anwar Ratol Special',
    variety: 'Anwar Ratol',
    price: 3200,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    description: 'Small in size but giant in flavor. The most aromatic variety.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Rahim Yar Khan',
    category: 'Seasonal'
  },
  {
    id: '4',
    name: 'Luxury Mango Gift Box',
    variety: 'Chaunsa',
    price: 4500,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Premium selected mangoes in a luxury wooden gift box.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Multan, Punjab',
    category: 'Gift'
  },
  {
    id: '5',
    name: 'Langra Organic Pack',
    variety: 'Langra',
    price: 1600,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'The green gem of Punjab. Unique tangy-sweet flavor.',
    sweetness: 4,
    harvestDate: 'July 2024',
    farmSource: 'Faisalabad',
    category: 'Seasonal'
  },
  {
    id: '6',
    name: 'White Chaunsa Premium',
    variety: 'White Chaunsa',
    price: 2800,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Late season delicacy. Incredibly sweet and long shelf life.',
    sweetness: 5,
    harvestDate: 'August 2024',
    farmSource: 'Multan',
    category: 'Premium'
  },
  {
    id: '7',
    name: 'Dusehri Sweet Pack',
    variety: 'Dusehri',
    price: 1500,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'The legendary Dusehri mango. Small, sweet, and fiberless.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Lucknow/Punjab',
    category: 'Seasonal'
  },
  {
    id: '8',
    name: 'Fajri Giant Box',
    variety: 'Fajri',
    price: 1900,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Large sized mangoes with a unique sweet and tangy profile.',
    sweetness: 4,
    harvestDate: 'July 2024',
    farmSource: 'Sindh',
    category: 'Premium'
  },
  {
    id: '9',
    name: 'Samar Bahisht Special',
    variety: 'Samar Bahisht',
    price: 2600,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    description: 'Literally "Fruit of Paradise". Heavenly aroma and taste.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Multan',
    category: 'Seasonal'
  },
  {
    id: '10',
    name: 'Neelum Late Season',
    variety: 'Neelum',
    price: 1400,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'Distinctive flavor and bright yellow color. Late season favorite.',
    sweetness: 4,
    harvestDate: 'August 2024',
    farmSource: 'Punjab',
    category: 'Seasonal'
  },
  {
    id: '11',
    name: 'Gulab Khas Premium',
    variety: 'Gulab Khas',
    price: 2100,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Known for its rosy aroma and sweet, reddish-yellow skin.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Sindh',
    category: 'Premium'
  },
  {
    id: '12',
    name: 'Sensation Mango Box',
    variety: 'Sensation',
    price: 1750,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'A beautiful red-skinned mango with a mild, sweet flavor.',
    sweetness: 4,
    harvestDate: 'July 2024',
    farmSource: 'Punjab',
    category: 'Seasonal'
  },
  {
    id: '13',
    name: 'Azeem Chaunsa Special',
    variety: 'Azeem Chaunsa',
    price: 2900,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    description: 'A late-season Chaunsa variety with exceptional sweetness.',
    sweetness: 5,
    harvestDate: 'August 2024',
    farmSource: 'Multan',
    category: 'Premium'
  },
  {
    id: '14',
    name: 'Lal Badshah Premium',
    variety: 'Lal Badshah',
    price: 2300,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'The "Red King" of mangoes. Vibrant color and rich taste.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Sindh',
    category: 'Premium'
  },
  {
    id: '15',
    name: 'Samar Bahisht',
    variety: 'Samar Bahisht',
    price: 1800,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'A heavenly variety with a unique aroma and taste.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Faisalabad',
    category: 'Premium'
  },
  {
    id: '16',
    name: 'Fajri Special',
    variety: 'Fajri',
    price: 1400,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'Large sized mangoes with a mild and pleasant flavor.',
    sweetness: 3,
    harvestDate: 'August 2024',
    farmSource: 'Multan',
    category: 'Seasonal'
  },
  {
    id: '17',
    name: 'Neelum Gold',
    variety: 'Neelum',
    price: 1300,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    description: 'A late-season variety with a distinct flavor and long shelf life.',
    sweetness: 4,
    harvestDate: 'August 2024',
    farmSource: 'Sindh',
    category: 'Seasonal'
  },
  {
    id: '18',
    name: 'Maldah Premium',
    variety: 'Maldah',
    price: 1900,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'A highly sought-after variety known for its rich and creamy texture.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Punjab',
    category: 'Premium'
  },
  {
    id: 'g1',
    name: 'Royal Sindhri Gift Box',
    variety: 'Sindhri',
    price: 3500,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Premium selected Sindhri mangoes in a royal velvet-lined box.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Mirpur Khas',
    category: 'Gift'
  },
  {
    id: 'g2',
    name: 'Imperial Anwar Ratol Box',
    variety: 'Anwar Ratol',
    price: 4800,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    description: 'The finest Anwar Ratol mangoes, hand-picked for perfection.',
    sweetness: 5,
    harvestDate: 'June 2024',
    farmSource: 'Rahim Yar Khan',
    category: 'Gift'
  },
  {
    id: 'g3',
    name: 'Golden Langra Gift Pack',
    variety: 'Langra',
    price: 3200,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'A traditional gift pack featuring the aromatic Langra mango.',
    sweetness: 4,
    harvestDate: 'July 2024',
    farmSource: 'Faisalabad',
    category: 'Gift'
  },
  {
    id: 'g4',
    name: 'White Chaunsa Luxury Box',
    variety: 'White Chaunsa',
    price: 4200,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    description: 'Premium White Chaunsa mangoes in an elegant wooden chest.',
    sweetness: 5,
    harvestDate: 'August 2024',
    farmSource: 'Multan',
    category: 'Gift'
  },
  {
    id: 'g5',
    name: 'Mix Variety Celebration Box',
    variety: 'Chaunsa',
    price: 5500,
    weightOptions: [9, 10, 11, 12, 13, 14, 15],
    selectedWeight: 9,
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'A large celebration box containing a mix of the best seasonal varieties.',
    sweetness: 5,
    harvestDate: 'July 2024',
    farmSource: 'Various',
    category: 'Gift'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'How to Store Mangoes for Maximum Freshness',
    excerpt: 'Learn the secrets to keeping your mangoes fresh and sweet for weeks.',
    content: 'Storing mangoes correctly is an art. First, keep them at room temperature until they are fully ripe. Once ripe, you can refrigerate them for up to 5 days. Avoid placing them in plastic bags as they need to breathe...',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    date: 'June 10, 2024',
    author: 'Farm Manager',
    category: 'Mango Care'
  },
  {
    id: 'b2',
    title: '5 Delicious Mango Recipes for the Summer',
    excerpt: 'From Mango Lassi to Mango Salsa, discover new ways to enjoy the king of fruits.',
    content: 'Summer is incomplete without mangoes. Try our signature Mango Lassi: blend ripe mango pulp with yogurt, a splash of milk, and a pinch of cardamom. For a savory twist, make Mango Salsa with diced mango, red onion, cilantro, and lime juice...',
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    date: 'June 12, 2024',
    author: 'Chef Maria',
    category: 'Recipes'
  },
  {
    id: 'b3',
    title: 'The Health Benefits of Mangoes: A Deep Dive',
    excerpt: 'Discover why mangoes are called the "King of Fruits" and how they can improve your health.',
    content: 'Mangoes are not just delicious; they are a nutritional powerhouse. Rich in Vitamin C, Vitamin A, and fiber, they support immune function, eye health, and digestion. They also contain antioxidants like mangiferin, which has anti-inflammatory properties...',
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    date: 'June 15, 2024',
    author: 'Dr. Nutrition',
    category: 'Health'
  },
  {
    id: 'b4',
    title: 'Sustainable Farming: Our Commitment to the Earth',
    excerpt: 'Learn about the eco-friendly practices we use in our orchards to protect the environment.',
    content: 'At MangoMart, we believe in farming that gives back to the earth. We use organic fertilizers, drip irrigation to save water, and natural pest control methods. Our goal is to provide the highest quality fruit while preserving the land for future generations...',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    date: 'June 18, 2024',
    author: 'Zia-ur-Rehman',
    category: 'Sustainability'
  },
  {
    id: 'b5',
    title: 'The History of Mangoes in the Subcontinent',
    excerpt: 'A journey through time, from the Mughal era to the modern day.',
    content: 'Mangoes have been cultivated in the subcontinent for over 4,000 years. Mughal emperors like Akbar were so fond of them that they planted massive orchards like the Lakhi Bagh in Darbhanga, which contained 100,000 mango trees...',
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    date: 'June 20, 2024',
    author: 'Historian Ali',
    category: 'History'
  },
  {
    id: 'b6',
    title: 'Exporting the Taste of Pakistan to the World',
    excerpt: 'How we ensure our mangoes reach international markets in perfect condition.',
    content: 'Exporting mangoes requires precision. From hot water treatment to careful packaging and temperature-controlled shipping, every step is crucial. We take pride in sharing the unique taste of Pakistani mangoes with fruit lovers across the globe...',
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&q=80&w=800',
    date: 'June 22, 2024',
    author: 'Export Manager',
    category: 'Business'
  }
];
